export const CHANGE_TEAM_NUMBER = "CHANGE_TEAM_NUMBER";
export const CHANGE_COLLECTION_TITLE = "CHANGE_COLLECTION_TITLE";
export const CHANGE_CURRENT_MEMBER = "CHANGE_CURRENT_MEMBER";
export const CHANGE_TOTAL_MEMBER = "CHANGE_TOTAL_MEMBER";
export const CHANGE_TEAM_NAME = "CHANGE_TEAM_NAME";
export const CHANGE_TEAM_IMG = "CHANGE_TEAM_IMG";
export const CHANGE_TEAM_CITY = "CHANGE_TEAM_CITY";
export const CHANGE_TEAM_LOC = "CHANGE_TEAM_LOC";
export const CHANGE_TEAM_GENDER = "CHANGE_TEAM_GENDER";
export const CHANGE_VIEW_COUNT = "CHANGE_VIEW_COUNT";
export const CHANGE_ACTIVE_STATUS = "CHANGE_ACTIVE_STATUS";
export const CHANGE_WRITTEN_DATE = "CHANGE_WRITTEN_DATE";
export const RESET_STATE = "RESET_STATE";

export const changeTeamNumber = (teamNumber) => ({ type: CHANGE_TEAM_NUMBER, payload: teamNumber });
export const changeCollectionTitle = (collectionTitle) => ({ type: CHANGE_COLLECTION_TITLE, payload: collectionTitle });
export const changeCurrentMember = (currentMember) => ({ type: CHANGE_CURRENT_MEMBER, payload: currentMember });
export const changeTotalMember = (totalMember) => ({ type: CHANGE_TOTAL_MEMBER, paylaod: totalMember });
export const changeTeamName = (teamName) => ({ type: CHANGE_TEAM_NAME, payload: teamName });
export const changeTeamImg = (teamImg) => ({ type: CHANGE_TEAM_IMG, payload: teamImg });
export const changeTeamCity = (teamCity) => ({ type: CHANGE_TEAM_CITY, payload: teamCity });
export const changeTeamLoc = (teamLoc) => ({ type: CHANGE_TEAM_LOC, payload: teamLoc });
export const changeTeamGender = (teamGender) => ({ type: CHANGE_TEAM_GENDER, payload: teamGender });
export const changeViewCount = (viewCount) => ({ type: CHANGE_VIEW_COUNT, payload: viewCount });
export const changeActiveStatus = (activeStatus) => ({type: CHANGE_ACTIVE_STATUS, payload: activeStatus});
export const changeWrittenDate = (writtenDate) => ({type: CHANGE_WRITTEN_DATE, payload: writtenDate});
export const resetState = () => ({ type: RESET_STATE });